export const GET_SINGLE_USER = "GET_SINGLE_USER"

export const MAIN_LOADER = "MAIN_LOADER"

export const REGISTER_LOGIN_SIGNOUT_USER = "REGISTER_LOGIN_SIGNOUT_USER"

export const FIREBASE_LOADER = "FIREBASE_LOADER"

export const BUY_TICKETS = "BUY_TICKETS"

export const SELECT_SEATS_FOR_PAYMENT = "SELECT_SEATS_FOR_PAYMENT"

export const GET_ALL_TICKETS = "GET_ALL_TICKETS"

export const CANCEL_SEATS = "CANCEL_SEATS"

export const UPDATE_SESSION_TURN = "UPDATE_SESSION_TURN"
